###
GET http://localhost:3000/api/credentials

###
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
    "email": "dennyssp689@unl.edu.ec",
    "password": "12345",
    "user": "024a76d4-9aad-4378-a741-00dd3dfc790c",     
    "rol": "6dd8da92-c885-4248-8868-771514208ac6"   
}

###
PUT http://localhost:3000/api/credentials/25dff42e-ff0f-4d37-8582-c6060ec892a2
Content-Type: application/json

{
    "email": "dennysspppo@unl.edu.ec",
    "lastpassword": "123457",
    "password": "123457",
    "state": true
}

###
GET http://localhost:3000/api/credentials/5b486820-ce9d-4961-9b3f-f78f2eee54b7

###
DELETE  http://localhost:3000/api/credentials/7b1cb599-d400-4298-bc7e-a9f21b333e28
Content-Type: application/json

{
    "email": "dennysspppo@unl.edu.ec",
    "password": "123457"
}